-- H2 Test Database Schema (H2-compatible SQL)
CREATE TABLE IF NOT EXISTS json_data (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    data VARCHAR(10000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xml_data (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    data VARCHAR(10000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_json_created_at ON json_data(created_at);
CREATE INDEX IF NOT EXISTS idx_xml_created_at ON xml_data(created_at);
